-- 1. Which customers generate the most revenue?
SELECT 
    c.customer_id,
    c.customer_name,
    SUM(o.quantity * o.unit_price) AS total_revenue_generated
FROM customers c
INNER JOIN orders o 
ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name
ORDER BY total_revenue_generated DESC;
/* 
This query ranks accounts by total financial value. Identifying top revenue-generating 
customers enables marketing and customer success teams to create VIP loyalty programs, 
provide proactive account management, and safeguard key cash-flow channels.
*/


-- 2. Which products perform best in each region?
WITH regional_product_revenue AS (
    SELECT 
        c.region,
        p.product_id,
        p.product_name,
        SUM(o.quantity * o.unit_price) AS product_revenue,
        RANK() OVER (PARTITION BY c.region ORDER BY SUM(o.quantity * o.unit_price) DESC) AS product_rank
    FROM orders o
    INNER JOIN customers c ON o.customer_id = c.customer_id
    INNER JOIN products p ON o.product_id = p.product_id
    GROUP BY c.region, p.product_id, p.product_name
)
SELECT region, product_id, product_name, product_revenue
FROM regional_product_revenue
WHERE product_rank = 1;
/* 
Performance Laptop emerged as the most performing product in 5 out of 7 regions. This indicate a great demand for 
performance laptops.
*/


-- 3. What is monthly revenue by category?
SELECT 
    EXTRACT(MONTH FROM o.order_date) AS order_month,
    p.category,
    SUM(o.quantity * o.unit_price) AS revenue
FROM orders o
INNER JOIN products p 
ON o.product_id = p.product_id
GROUP BY order_month, p.category
ORDER BY order_month ASC, revenue DESC;
/*  
This monthly cross-sectional breakdown tracks structural changes within product classifications over time. 
It shows whether specific fields (e.g., Computers vs. Displays) surge during particular quarters, helping 
the executive team forecast seasonal working capital and map yearly production timelines.
*/


-- 4. Are there customers with no orders?
SELECT 
    c.customer_id,
    c.customer_name,
    c.region
FROM customers c
LEFT JOIN orders o 
ON c.customer_id = o.customer_id
WHERE o.order_id IS NULL;
/*  
The query seeks to find customers without other. It turns out that all customers had an order.
*/


-- 5. Which categories contribute most to revenue?
SELECT 
    p.category,
    SUM(o.quantity * o.unit_price) AS revenue
FROM orders o
INNER JOIN products p ON o.product_id = p.product_id
GROUP BY p.category
ORDER BY revenue DESC;
/*  
Computers, Displays and Funiture are categories which contribute the most in revenue.
*/


-- 6. Are there noticeable customer purchasing patterns?
SELECT 
    c.customer_id,
    c.customer_name,
    COUNT(o.order_id) AS total_orders_placed
FROM customers c
INNER JOIN orders o 
ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name
ORDER BY total_orders_placed DESC;
/* 
The total orders placed by individual customers ranges from 9 to 14, only one customer had more than 14 orders.
*/


-- 7A. Is revenue heavily concentrated in particular regions or products?
-- [Regional Concentration]
SELECT c.region, 
SUM(o.quantity * o.unit_price) AS Revenue 
FROM customers AS c 
INNER JOIN orders AS o
ON
c.customer_id = o.customer_id
GROUP BY c.region
ORDER BY Revenue DESC;
/* 
Revenue is heavily concentrated in Greater Accra and Ashanti region, both generating 1,558,419.20 and 1,422,383.92
*/


--B. Is revenue concentrated in a particula product?
SELECT 
p.product_id,
p.product_name,
SUM(o.quantity*o.unit_price) AS revenue
FROM products p
INNER JOIN orders o
ON p.product_id = o.product_id
GROUP BY p.product_id, p.product_name
ORDER BY revenue DESC;
/*
This query provides revenue by product. This helps know the revenue generated by each product. Performance Laptop, 
office laptop, and Mini PC generated the most revenue.
*/

-- 8. Which salespersons are driving the highest profitability based on average order sizes?
SELECT 
    salesperson,
    COUNT(order_id) AS deals_closed,
    SUM(quantity * unit_price) AS total_sales_volume,
    AVG(quantity * unit_price) AS average_deal_value
FROM orders
GROUP BY salesperson
ORDER BY average_deal_value DESC;
/* 
The query identifies tital orders processed by each salesperson, as well as volume generated from it.
*/

